
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
public class Images_CGI extends javax.swing.JDialog {

    public static Images_CGI dialog;
    int month = java.util.Calendar.getInstance().get(java.util.Calendar.MONTH);
    int year = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
    String day = "";

    /**
     * Creates new form Images_CGI
     *
     * @param parent
     * @param modal
     * @throws java.io.IOException
     */
    public Images_CGI(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();
        minum_img.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/miii.png"))));
        /////////////////////
        f_f_f.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/Gray_left.jfif"))));
        f_f_s.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/Gray_right.jfif"))));
        f_f_t.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/images.png"))));

        s_s_f.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/Gray_left.jfif"))));
        s_s_s.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/Gray_right.jfif"))));
        s_s_t.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/images.png"))));
        c_d_f.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/blue_rigth_save.jpg"))));
        c_d_s.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/blue_left_save.jpg"))));//left
        c_d_t.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/close_c.png"))));

        r_d_f.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/Gray_left.jfif"))));
        r_d_s.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/Gray_right.jfif"))));
        r_d_t.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/images.png"))));

        r_d_f_f.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/Gray_left.jfif"))));
        r_d_f_s.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/Gray_right.jfif"))));
        r_d_f_t.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/images.png"))));

        r_d_s_f.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/Gray_left.jfif"))));
        r_d_s_s.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/Gray_right.jfif"))));//left_cement
        r_d_s_t.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/images.png"))));

        r_d_t_f.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/blue_rigth_save.jpg"))));
        r_d_t_s.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/blue_left_save.jpg"))));//left
        r_d_t_t.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/close_c.png"))));

        r_d_ff_f.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/blue_rigth_save.jpg"))));
        r_d_ff_s.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/blue_left_save.jpg"))));//left
        r_d_ff_t.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/close_c.png"))));

        r_d_fff_f.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/blue_rigth_save.jpg"))));
        r_d_fff_s.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/blue_left_save.jpg"))));//left
        r_d_fff_t.setIcon(new ImageIcon(ImageIO.read(getClass().getResourceAsStream("Images/close_c.png"))));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Top_Panel = new javax.swing.JPanel();
        add_tag_panel = new javax.swing.JPanel();
        minum_img = new javax.swing.JLabel();
        add_work_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cancle_button = new javax.swing.JButton();
        finish_button = new javax.swing.JButton();
        next_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Const_status = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Constru = new javax.swing.JComboBox<>();
        setion_com = new javax.swing.JTextField();
        work_method = new javax.swing.JComboBox<>();
        cable_instal = new javax.swing.JComboBox<>();
        footage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        performanec_check = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        choice_complete = new java.awt.Choice();
        fault_found = new java.awt.Choice();
        fault_equp = new java.awt.Choice();
        jLabel14 = new javax.swing.JLabel();
        delay_rea = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        first_fail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        second_fsil = new javax.swing.JTextField();
        f_f_f = new javax.swing.JButton();
        f_f_s = new javax.swing.JButton();
        f_f_t = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        s_s_f = new javax.swing.JButton();
        s_s_s = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        s_s_t = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        c_and_d_date = new javax.swing.JTextField();
        c_d_f = new javax.swing.JButton();
        c_d_s = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        c_d_t = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        injection_tag = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        lettes_request = new javax.swing.JTextField();
        r_d_ff_f = new javax.swing.JButton();
        r_d_ff_s = new javax.swing.JButton();
        r_d_ff_t = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        completed_date = new javax.swing.JTextField();
        r_d_fff_f = new javax.swing.JButton();
        r_d_fff_s = new javax.swing.JButton();
        r_d_fff_t = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        hold_remove = new javax.swing.JTextField();
        r_d_t_f = new javax.swing.JButton();
        r_d_t_s = new javax.swing.JButton();
        r_d_t_t = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        on_hold = new javax.swing.JTextField();
        r_d_s_s = new javax.swing.JButton();
        r_d_s_f = new javax.swing.JButton();
        r_d_s_t = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        remove_date_two = new javax.swing.JTextField();
        r_d_f_f = new javax.swing.JButton();
        r_d_f_s = new javax.swing.JButton();
        r_d_f_t = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        remove_date_one = new javax.swing.JTextField();
        r_d_f = new javax.swing.JButton();
        r_d_s = new javax.swing.JButton();
        r_d_t = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Top_Panel.setPreferredSize(new java.awt.Dimension(1188, 503));
        Top_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_tag_panel.setBackground(new java.awt.Color(255, 255, 255));
        add_tag_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add_tag_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add_tag_panel.add(minum_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 10, 10));

        add_work_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_work_label.setText("Add Work Task");
        add_tag_panel.add(add_work_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 160, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Work Task Attributes");
        add_tag_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Describe the Work Task attributes");
        add_tag_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 250, -1));

        Top_Panel.add(add_tag_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 110));

        cancle_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancle_button.setText("Cancel");
        Top_Panel.add(cancle_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 540, 70, -1));

        finish_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        finish_button.setText("Finish");
        Top_Panel.add(finish_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 540, 70, -1));

        next_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        next_button.setText("Next  >");
        Top_Panel.add(next_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, -1, -1));

        back_button.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back_button.setText("<  Back");
        Top_Panel.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("                                                                                                                              Beign modified by kxkonpi on 19/11/20 at 12:21:19 PM");
        Top_Panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 810, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Work Task Information");
        Top_Panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 820, 20));

        Const_status.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Const_status.setText("Construction Status");
        Top_Panel.add(Const_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 120, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText(" % Completed");
        Top_Panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 90, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Section % Complete ( Ft)");
        Top_Panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Work Method");
        Top_Panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 90, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Type Cable Installed");
        Top_Panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 120, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Final Actual Footage");
        Top_Panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 120, 20));

        Top_Panel.add(Constru, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 100, -1));

        setion_com.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        setion_com.setText("0");
        Top_Panel.add(setion_com, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 100, -1));

        Top_Panel.add(work_method, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 100, 20));

        Top_Panel.add(cable_instal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 100, 20));
        Top_Panel.add(footage, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Completde-No Rehab Performed(4%)");
        Top_Panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 210, 20));

        performanec_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performanec_checkActionPerformed(evt);
            }
        });
        Top_Panel.add(performanec_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 20, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Fault Found ?");
        Top_Panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 80, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Faulted Equipment");
        Top_Panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, 20));
        Top_Panel.add(choice_complete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 100, -1));
        Top_Panel.add(fault_found, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 80, -1));
        Top_Panel.add(fault_equp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 200, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText(" Hold / Delay Reason");
        Top_Panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 120, 20));

        Top_Panel.add(delay_rea, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 200, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText(" Fault Repair Date 1st Failure");
        Top_Panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, 20));
        Top_Panel.add(first_fail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 80, 20));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("  Fault Repair Date 2nd Failure");
        Top_Panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, 20));
        Top_Panel.add(second_fsil, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 80, -1));
        Top_Panel.add(f_f_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 25, 25));
        Top_Panel.add(f_f_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 25, 25));
        Top_Panel.add(f_f_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 25, 25));

        jButton8.setText("jButton8");
        Top_Panel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 25, 25));
        Top_Panel.add(s_s_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 25, 25));
        Top_Panel.add(s_s_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 25, 25));

        jButton11.setText("jButton8");
        Top_Panel.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 25, 25));
        Top_Panel.add(s_s_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 25, 25));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Replacement / injection C & D Date");
        Top_Panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, 20));
        Top_Panel.add(c_and_d_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 80, -1));
        Top_Panel.add(c_d_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 25, 25));
        Top_Panel.add(c_d_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 25, 25));

        jButton15.setText("jButton8");
        Top_Panel.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 25, 25));
        Top_Panel.add(c_d_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 25, 25));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText(" Injection Tag#");
        Top_Panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 90, -1));
        Top_Panel.add(injection_tag, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 210, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText(" Date Proactive Letters Requested");
        Top_Panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, 20));
        Top_Panel.add(lettes_request, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 80, -1));
        Top_Panel.add(r_d_ff_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 280, 25, 25));
        Top_Panel.add(r_d_ff_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 280, 25, 25));
        Top_Panel.add(r_d_ff_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 280, 25, 25));

        jButton24.setText("jButton8");
        Top_Panel.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 280, 25, 25));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Estimated Proactive Completed date");
        Top_Panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, 20));
        Top_Panel.add(completed_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, 80, -1));
        Top_Panel.add(r_d_fff_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 310, 25, 25));
        Top_Panel.add(r_d_fff_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 310, 25, 25));
        Top_Panel.add(r_d_fff_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 310, 25, 25));

        jButton28.setText("jButton8");
        Top_Panel.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 310, 25, 25));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Date Hold Removed");
        Top_Panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, -1, 20));
        Top_Panel.add(hold_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 80, -1));
        Top_Panel.add(r_d_t_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 250, 25, 25));
        Top_Panel.add(r_d_t_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 250, 25, 25));
        Top_Panel.add(r_d_t_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 250, 25, 25));

        jButton32.setText("jButton8");
        Top_Panel.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 250, 25, 25));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText(" Date Placed On Hold");
        Top_Panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, -1, 20));
        Top_Panel.add(on_hold, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 80, -1));
        Top_Panel.add(r_d_s_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 220, 25, 25));
        Top_Panel.add(r_d_s_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 220, 25, 25));
        Top_Panel.add(r_d_s_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 220, 25, 25));

        jButton36.setText("jButton8");
        jButton36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton36MouseClicked(evt);
            }
        });
        Top_Panel.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 220, 25, 25));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("  Pri. GS#2 Removal date");
        Top_Panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, -1, 20));
        Top_Panel.add(remove_date_two, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 80, -1));
        Top_Panel.add(r_d_f_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, 25, 25));
        Top_Panel.add(r_d_f_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 190, 25, 25));
        Top_Panel.add(r_d_f_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 190, 25, 25));

        jButton40.setText("jButton8");
        Top_Panel.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 190, 25, 25));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("  Pri. GS#1 Removal date");
        Top_Panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, 20));
        Top_Panel.add(remove_date_one, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, 80, -1));
        Top_Panel.add(r_d_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 160, 25, 25));
        Top_Panel.add(r_d_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, 25, 25));
        Top_Panel.add(r_d_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 160, 25, 25));

        jButton44.setText("jButton8");
        Top_Panel.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 160, 25, 25));
        Top_Panel.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Top_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Top_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void performanec_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performanec_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_performanec_checkActionPerformed

    private void jButton36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton36MouseClicked

    }//GEN-LAST:event_jButton36MouseClicked

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
        dialog = new Images_CGI(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Const_status;
    private javax.swing.JComboBox<String> Constru;
    private javax.swing.JPanel Top_Panel;
    private javax.swing.JPanel add_tag_panel;
    private javax.swing.JLabel add_work_label;
    private javax.swing.JButton back_button;
    private javax.swing.JTextField c_and_d_date;
    private javax.swing.JButton c_d_f;
    private javax.swing.JButton c_d_s;
    private javax.swing.JButton c_d_t;
    private javax.swing.JComboBox<String> cable_instal;
    private javax.swing.JButton cancle_button;
    private java.awt.Choice choice_complete;
    private javax.swing.JTextField completed_date;
    private javax.swing.JComboBox<String> delay_rea;
    private javax.swing.JButton f_f_f;
    private javax.swing.JButton f_f_s;
    private javax.swing.JButton f_f_t;
    private java.awt.Choice fault_equp;
    private java.awt.Choice fault_found;
    private javax.swing.JButton finish_button;
    private javax.swing.JTextField first_fail;
    private javax.swing.JTextField footage;
    private javax.swing.JTextField hold_remove;
    private javax.swing.JTextField injection_tag;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton8;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lettes_request;
    private javax.swing.JLabel minum_img;
    private javax.swing.JButton next_button;
    private javax.swing.JTextField on_hold;
    private javax.swing.JCheckBox performanec_check;
    private javax.swing.JButton r_d_f;
    private javax.swing.JButton r_d_f_f;
    private javax.swing.JButton r_d_f_s;
    private javax.swing.JButton r_d_f_t;
    private javax.swing.JButton r_d_ff_f;
    private javax.swing.JButton r_d_ff_s;
    private javax.swing.JButton r_d_ff_t;
    private javax.swing.JButton r_d_fff_f;
    private javax.swing.JButton r_d_fff_s;
    private javax.swing.JButton r_d_fff_t;
    private javax.swing.JButton r_d_s;
    private javax.swing.JButton r_d_s_f;
    private javax.swing.JButton r_d_s_s;
    private javax.swing.JButton r_d_s_t;
    private javax.swing.JButton r_d_t;
    private javax.swing.JButton r_d_t_f;
    private javax.swing.JButton r_d_t_s;
    private javax.swing.JButton r_d_t_t;
    private javax.swing.JTextField remove_date_one;
    private javax.swing.JTextField remove_date_two;
    private javax.swing.JButton s_s_f;
    private javax.swing.JButton s_s_s;
    private javax.swing.JButton s_s_t;
    private javax.swing.JTextField second_fsil;
    private javax.swing.JTextField setion_com;
    private javax.swing.JComboBox<String> work_method;
    // End of variables declaration//GEN-END:variables
}
